### ISSUE TITLE
Error "There is no open cursor with id" when executing a find command

### ISSUE THREAD

**Issue by jordipala** [torodb/torodb#16]
I am creating an empty postgresql database, starting torodb and executing the following code:

## Dependencies

 <dependency>
        <groupId>org.mongodb</groupId>
        <artifactId>mongo-java-driver</artifactId>
        <version>2.13.1</version>
    </dependency>

## Insert new data in an empty torodb database

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
 
/**
 * Java MongoDB : Insert a bunch of documents
 * 
 */
public class MassiveInsert {
  public static void main(String[] args) {
 
    try {
		Mongo mongo = new Mongo("localhost", 27017);
		DB db = mongo.getDB("db");
	 
		DBCollection collection = db.getCollection("ships");
	 
		for(int i=0; i<1500; i++){
			insert(collection, i);
		}
    } catch (Exception e) {
    	e.printStackTrace();
    }
 
  }

	private static void insert(DBCollection collection, int index) {
		System.out.println("BasicDBObject example..." + index);
		BasicDBObject document = new BasicDBObject();
		document.put("name", "USS Enterprise");
		document.put("ship_id", index);
	 
		BasicDBObject documentDetail = new BasicDBObject();
		documentDetail.put("active", "true");
		documentDetail.put("engines", 99);	
		document.put("detail", documentDetail);
		collection.insert(document);
	}
}

## Retrieve the data

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.Mongo;
 
/**
 * Java MongoDB : Retrieve documents
 * 
 */
public class MassiveReader {
  public static void main(String[] args) {
 
    try {
	 	Mongo mongo = new Mongo("localhost", 27017);
		DB db = mongo.getDB("db");

		DBCollection collection = db.getCollection("ships");
		
		DBCursor cursorDocJSON = collection.find();
		while (cursorDocJSON.hasNext()) {
			System.out.println(cursorDocJSON.next());
		}
    } catch (Exception e) {
    	e.printStackTrace();
    }
  }
}

# Error output

62650 [torod-session-5] ERROR c.t.t.d.e.DefaultExecutorFactory - Session executor exception 
com.torodb.torod.core.exceptions.ToroRuntimeException: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.onFail(ReadCursorCallable.java:89) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.onFail(ReadCursorCallable.java:39) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:22) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.DefaultSessionExecutor$SessionRunnable.call(DefaultSessionExecutor.java:196) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:73) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:39) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:20) ~[torodb-0.20-jar-with-dependencies.jar:na]
        ... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.sql.AbstractSqlDbWrapper.getGlobalCursor(AbstractSqlDbWrapper.java:219) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.LazyDbWrapper.getGlobalCursor(LazyDbWrapper.java:68) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:64) ~[torodb-0.20-jar-with-dependencies.jar:na]
        ... 7 common frames omitted
62655 [nioEventLoopGroup-3-4] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.torodb.torod.core.exceptions.ToroRuntimeException: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.toro.torod.connection.DefaultCursorManager.readCursor(DefaultCursorManager.java:137) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.mongowp.mongoserver.api.toro.ToroRequestProcessor.getMore(ToroRequestProcessor.java:203) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.eightkdata.mongowp.mongoserver.RequestMessageObjectHandler.channelRead(RequestMessageObjectHandler.java:65) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [torodb-0.20-jar-with-dependencies.jar:na]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [torodb-0.20-jar-with-dependencies.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.util.concurrent.ExecutionException: com.torodb.torod.core.exceptions.ToroRuntimeException: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_25]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_25]
        at com.toro.torod.connection.DefaultCursorManager.readCursor(DefaultCursorManager.java:115) ~[torodb-0.20-jar-with-dependencies.jar:na]
        ... 19 common frames omitted
Caused by: com.torodb.torod.core.exceptions.ToroRuntimeException: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.onFail(ReadCursorCallable.java:89) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.onFail(ReadCursorCallable.java:39) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:22) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.DefaultSessionExecutor$SessionRunnable.call(DefaultSessionExecutor.java:196) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
        ... 1 common frames omitted
Caused by: com.torodb.torod.core.exceptions.UserToroException: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:73) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:39) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:20) ~[torodb-0.20-jar-with-dependencies.jar:na]
        ... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: There is no open cursor with id com.torodb.torod.core.cursors.CursorId@150
        at com.torodb.torod.db.sql.AbstractSqlDbWrapper.getGlobalCursor(AbstractSqlDbWrapper.java:219) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.LazyDbWrapper.getGlobalCursor(LazyDbWrapper.java:68) ~[torodb-0.20-jar-with-dependencies.jar:na]
        at com.torodb.torod.db.executor.jobs.ReadCursorCallable.failableCall(ReadCursorCallable.java:64) ~[torodb-0.20-jar-with-dependencies.jar:na]
        ... 7 common frames omitted

**Comment by ahachete** [comment]
Hi jordipala, I can confirm the issue, marked as bug. We will try to fix it asap

**Comment by ahachete** [comment]
Hi Jordi. I have submitted a patch that should fix this issue. It is on the devel branch of the repository. Could you please confirm if it fixes your problem?

Thank you,

Álvaro
