### ISSUE TITLE
Issues with mongorestore will evaluating ToroDB

### ISSUE THREAD

**Issue by zopyx** [torodb/torodb#17]
I am running latest ToroDB against Postgres 9.4

I am trying to use mongorestore to reimport some project data through ToroDB.

No success with mongorestore 2.6:

connected to: 127.0.0.1
2015-04-27T18:20:10.812+0200 monitoring/sw-duisburg2.einkaeufe.bson
2015-04-27T18:20:10.812+0200 	going into namespace [monitoring.sw-duisburg2.einkaeufe]
6 objects found
2015-04-27T18:20:10.814+0200 	Creating index: { key: { _id: 1 }, ns: "monitoring.sw-duisburg2.einkaeufe", name: "_id_" }
2015-04-27T18:20:11.064+0200 Assertion: 16441:Error calling getLastError: EOO
2015-04-27T18:20:11.068+0200 0x11f6f21 0x119a3e9 0x117ef96 0x117f4ec 0x7702fb 0x774755 0x778957 0x778121 0x77df5a 0x116fb6d 0x1172d57 0x11737f2 0x7fd256be4d5d 0x7639c9 
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN5mongo15printStackTraceERSo+0x21) [0x11f6f21]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN5mongo10logContextEPKc+0x159) [0x119a3e9]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN5mongo11msgassertedEiPKc+0xe6) [0x117ef96]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore() [0x117f4ec]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN7Restore11createIndexEN5mongo7BSONObjEb+0x107b) [0x7702fb]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN7Restore22processFileAndMetadataERKN5boost11filesystem34pathERKSs+0x1b45) [0x774755]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN7Restore9drillDownEN5boost11filesystem34pathEbbbb+0xe47) [0x778957]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN7Restore9drillDownEN5boost11filesystem34pathEbbbb+0x611) [0x778121]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN7Restore5doRunEv+0x55a) [0x77df5a]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN5mongo8BSONTool3runEv+0x10d) [0x116fb6d]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(_ZN5mongo4Tool4mainEiPPcS2_+0xb7) [0x1172d57]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore(main+0x42) [0x11737f2]
 /lib64/libc.so.6(__libc_start_main+0xfd) [0x7fd256be4d5d]
 /opt/mongodb-linux-x86_64-2.6.7/bin/mongorestore() [0x7639c9]

No errors on the ToroDB side (running with --debug)

Import with mongorestore 3.0:

[ajung@dev1 vik.monitoring_buildout]$ /opt/mongodb-linux-x86_64-3.0.0/bin/mongorestore -d monitoring monitoring
2015-04-27T18:21:21.914+0200	Failed: error connecting to db server: no reachable servers

On the ToroDB side:

56494 [nioEventLoopGroup-3-8] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53693, requestId=3, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "ismaster" : 1}, returnFieldsSelector=null} 
256995 [nioEventLoopGroup-3-1] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53694, requestId=1, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "getnonce" : 1}, returnFieldsSelector=null} 
256996 [nioEventLoopGroup-3-1] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53694, requestId=3, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "ismaster" : 1}, returnFieldsSelector=null} 
257998 [nioEventLoopGroup-3-2] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53695, requestId=1, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "getnonce" : 1}, returnFieldsSelector=null} 
257999 [nioEventLoopGroup-3-2] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53695, requestId=3, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "ping" : 1}, returnFieldsSelector=null} 
257999 [nioEventLoopGroup-3-3] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53696, requestId=1, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "getnonce" : 1}, returnFieldsSelector=null} 
258000 [nioEventLoopGroup-3-3] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=53696, requestId=3, database='admin', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "ismaster" : 1}, returnFieldsSelector=null} 
258001 [nioEventLoopGroup-3-3] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_25]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[na:1.7.0_25]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[na:1.7.0_25]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[na:1.7.0_25]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[na:1.7.0_25]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447) ~[torodb.jar:na]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) ~[torodb.jar:na]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) ~[torodb.jar:na]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[torodb.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[torodb.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[torodb.jar:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[torodb.jar:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[torodb.jar:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[torodb.jar:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[torodb.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_25]

**Comment by grivescorbett** [comment]
I am also getting an error when using mongorestore

    2015-04-30T17:17:06.187-0400 path/to/my_collection.bson
    2015-04-30T17:17:06.188-0400 	going into namespace [torod.my_collection]
    903 objects found
    2015-04-30T17:17:06.197-0400 	Creating index: { key: { _id: 1 }, name: "_id_", ns: "torod.my_collection" }
    2015-04-30T17:17:07.656-0400 Assertion: 16441:Error calling getLastError: EOO
    2015-04-30T17:17:07.660-0400 0x10406060a 0x10400c9d5 0x103ffa8f4 0x103ffa74a 0x103875f68 0x10387ffb8 0x103882368 0x1038819a9 0x103871730 0x103ff01cf     0x103fee0d1 0x103ff1682 0x7fff9113c5c9
     0   mongorestore                        0x000000010406060a _ZN5mongo15printStackTraceERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEE + 58
     1   mongorestore                        0x000000010400c9d5 _ZN5mongo10logContextEPKc + 453
     2   mongorestore                        0x0000000103ffa8f4 _ZN5mongo11msgassertedEiPKc + 420
     3   mongorestore                        0x0000000103ffa74a _ZN5mongo11msgassertedEiRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE + 26
     4   mongorestore                        0x0000000103875f68 _ZN7Restore11createIndexEN5mongo7BSONObjEb + 2872
     5   mongorestore                        0x000000010387ffb8     _ZN7Restore22processFileAndMetadataERKN5boost11filesystem34pathERKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 9160
     6   mongorestore                        0x0000000103882368 _ZN7Restore9drillDownEN5boost11filesystem34pathEbbbb + 4008
     7   mongorestore                        0x00000001038819a9 _ZN7Restore9drillDownEN5boost11filesystem34pathEbbbb + 1513
     8   mongorestore                        0x0000000103871730 _ZN7Restore5doRunEv + 11472
     9   mongorestore                        0x0000000103ff01cf _ZN5mongo8BSONTool3runEv + 223
     10  mongorestore                        0x0000000103fee0d1 _ZN5mongo4Tool4mainEiPPcS2_ + 1537
     11  mongorestore                        0x0000000103ff1682 main + 66
     12  libdyld.dylib                       0x00007fff9113c5c9 start + 1
    assertion: 16441 Error calling getLastError: EOO
