### ISSUE TITLE
Upsert updates are not supported

### ISSUE THREAD

**Issue by okapies** [torodb/torodb#21]
It is related to #18 and #19. After initialization (`npm start`) on Let's Chat is successful, accessing to `http://localhost:5000/login` produces the following errors:

```
684219 [nioEventLoopGroup-3-2] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=54056, requestId=7, database='letschat', collection='$cmd', numberToSkip=0, numberToReturn=-1, document={ "update" : "sessions" , "updates" : [ { "q" : { "_id" : "rY0RvMeYlwWHOy9o23zT_i8FfIkk1xZ5"} , "u" : { "_id" : "rY0RvMeYlwWHOy9o23zT_i8FfIkk1xZ5" , "session" : "{\"cookie\":{\"originalMaxAge\":null,\"expires\":null,\"secure\":false,\"httpOnly\":true,\"path\":\"/\"},\"passport\":{}}" , "expires" : { "$date" : 1436577724335}} , "upsert" : true}] , "ordered" : true , "writeConcern" : { }}, returnFieldsSelector=null} 
684221 [nioEventLoopGroup-3-2] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
com.torodb.torod.core.exceptions.UserToroException: Upsert updates are not supported
    at com.toro.torod.connection.DefaultToroTransaction.update(DefaultToroTransaction.java:210) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.mongowp.mongoserver.api.toro.ToroQueryCommandProcessor.update(ToroQueryCommandProcessor.java:197) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.eightkdata.mongowp.mongoserver.api.QueryCommandProcessor$ProcessorCaller.update(QueryCommandProcessor.java:226) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.eightkdata.mongowp.mongoserver.api.commands.QueryAndWriteOperationsQueryCommand$4.doCall(QueryAndWriteOperationsQueryCommand.java:69) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    ...
684324 [nioEventLoopGroup-3-6] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=54052, requestId=8, database='letschat', collection='sessions', numberToSkip=0, numberToReturn=-1, document={ "_id" : "rY0RvMeYlwWHOy9o23zT_i8FfIkk1xZ5" , "$or" : [ { "expires" : { "$exists" : false}} , { "expires" : { "$gt" : { "$date" : 1435368124437}}}]}, returnFieldsSelector=null} 
684326 [nioEventLoopGroup-3-6] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
com.torodb.torod.core.exceptions.ToroImplementationException: DocValue 2015-06-27T10:22:04.437 is not translatable to basic values
    at com.torodb.torod.core.subdocument.values.ValueFactory.fromDocValue(ValueFactory.java:91) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateGtOperand(BasicQueryTranslator.java:497) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQuery(BasicQueryTranslator.java:428) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQueries(BasicQueryTranslator.java:393) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    ...
684488 [nioEventLoopGroup-3-7] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=54053, requestId=9, database='letschat', collection='sessions', numberToSkip=0, numberToReturn=-1, document={ "_id" : "rY0RvMeYlwWHOy9o23zT_i8FfIkk1xZ5" , "$or" : [ { "expires" : { "$exists" : false}} , { "expires" : { "$gt" : { "$date" : 1435368124604}}}]}, returnFieldsSelector=null} 
684489 [nioEventLoopGroup-3-7] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
com.torodb.torod.core.exceptions.ToroImplementationException: DocValue 2015-06-27T10:22:04.604 is not translatable to basic values
    at com.torodb.torod.core.subdocument.values.ValueFactory.fromDocValue(ValueFactory.java:91) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateGtOperand(BasicQueryTranslator.java:497) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQuery(BasicQueryTranslator.java:428) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQueries(BasicQueryTranslator.java:393) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    ...
684508 [nioEventLoopGroup-3-8] DEBUG c.e.m.m.RequestMessageObjectHandler - Received message type: OP_QUERY, data: QueryMessage{clientAddress=127.0.0.1, clientPort=54054, requestId=10, database='letschat', collection='sessions', numberToSkip=0, numberToReturn=-1, document={ "_id" : "rY0RvMeYlwWHOy9o23zT_i8FfIkk1xZ5" , "$or" : [ { "expires" : { "$exists" : false}} , { "expires" : { "$gt" : { "$date" : 1435368124626}}}]}, returnFieldsSelector=null} 
684509 [nioEventLoopGroup-3-8] ERROR c.e.m.m.RequestMessageObjectHandler - Error while processing request 
com.torodb.torod.core.exceptions.ToroImplementationException: DocValue 2015-06-27T10:22:04.626 is not translatable to basic values
    at com.torodb.torod.core.subdocument.values.ValueFactory.fromDocValue(ValueFactory.java:91) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateGtOperand(BasicQueryTranslator.java:497) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQuery(BasicQueryTranslator.java:428) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.torodb.translator.BasicQueryTranslator.translateSubQueries(BasicQueryTranslator.java:393) ~[torodb-0.23-SNAPSHOT-jar-with-dependencies.jar:na]
    ...
```

**Comment by gortiz** [comment]
Hi,

First of all, thanks for your feedback. Talking about the issue... we know
upsert updates are not supported on ToroDB 0.23. When CRUD actions were
implemented, we decided to not implement that feature because the upsert
language supported by MongoDB is quite complex. We can easily implement a
subset of that language (and I am sure that subset would be enough for most
users) but we are focused on replication right now. The good new is that we
need to support upsert to support replication, so we hope we will release a
new ToroDB version in the following weeks that will support upsert and at
least a subset of replication features.

Please stay in touch,

Gonzalo Oritz

2015-06-27 3:31 GMT+02:00 Yuta Okamoto <notifications@github.com>:

**Comment by okapies** [comment]
That's a great news! I'm looking forward to it.

**Comment by graingert** [comment]
@gortiz has upsert support been enabled?

**Comment by gortiz** [comment]
Hi @graingert,

We were able to replicate oplog without upserts, so it is not yet implemented. To be honest, the abstract operation (upsert) is not very difficult to implement, but MongoDB supports some very specific operations (like $) that are not very well documented and a little bit tricky. As we came from the SQL world, we thought the operation was not very used and decided to not implement it until we had time to find a _total implementation_ that were as expressive as MongoDB is. In the SQL world the upsert operation is not so important, as you can (almost always) replace it with a select-for-update + insert/update in a trasaction. Of course this is not possible on MongoDB, as it does not provide transactions and we totally undertand upsert is, in fact, a very important operation on the MongoDB ecosystem.

Right now we are pretty busy (funny thing, we are again improving the replication layer) so I cannot estimate when the upsert operation will be ready. On the other hand, a _partial_ implementation that fails only when not supported operations (like $) are received should be not-very-difficult to implement by a new contributor (the the method that should be implemented is [this one](https://github.com/torodb/torodb/blob/devel/torod/connection/src/main/java/com/toro/torod/connection/DefaultToroTransaction.java#L381)). You can try to do it if you feel brave enough ;-)

PS: Right now the update is, by far, the CRUD operation that has the worst implementation (in terms of efficiency) on ToroDB, so don't blame us if you found better ways to do it. We know it has to be improved, it is just a matter of time until we will do it.

**Comment by teoincontatto** [comment]
We have added basic upsert support with #84 and #86 that allow to replace or create an entire document.

**Comment by andyka** [comment]
Hi all, is this functionality still on the roadmap? 

A bit of background: I am trying to port our app (which uses MongoDB) to RaspberryPi 3. MongoDB limits storage to 2 GB when on 32-bit system. While RPi 3 has a 64-bit CPU, there is no 64-bit kernel drivers available (and no ETA for them), so I started looking for other solutions and found ToroDB. I love the solution (it would allow us to migrate slowly to PostgreSQL, which would be awesome - we are not that thrilled about MongoDB anymore), but the way I see it there are two major obstacles to this:

    - protocol must be 100% compatible (not necessarily with the latest version!), which includes upserts
    - performance (with the first test inserts were quite slow comapred to MongoDB)

We can live with performance problems (for now), but upserts and possible other incompatibilities are a deal-breaker for us. Note that there is no need to be compatible with latest MongoDB, it's enough to cover just a specific version. 

Best regards!

**Comment by ahachete** [comment]
Hi andyka.

Thank you for your interest. Yes, there is going to be some support for upsert soon. It will be limited to certain use cases but it will cover most of the usual usage, so will probably work for you.

There is a new version with many improvements due out soon. Please keep watching :)

Running >2GB mongo-like databases is a very interesting use case for us.

**Comment by gortiz** [comment]
I close this issue, as it does not apply to the new version.

@andyka your case seems very interesting... can you wrote about it on our mail group?
