### ISSUE TITLE
Unable to start when use Amazon RDS

### ISSUE THREAD

**Issue by evanccnyc** [torodb/torodb#23]
Hi there,

When I try and start torodb with an Amazon RDS backend (Postgres 9.4) with root user I get the following error:

```
Exception in thread "Thread-3" java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: must be owner of type character varying or type jsonb
	at com.torodb.torod.db.sql.AbstractSqlDbWrapper.initialize(AbstractSqlDbWrapper.java:116)
	at com.torodb.torod.db.executor.DefaultExecutorFactory.initialize(DefaultExecutorFactory.java:87)
	at com.toro.torod.connection.DefaultTorod.start(DefaultTorod.java:67)
	at com.torodb.Main.run(Main.java:155)
	at com.torodb.Main.access$100(Main.java:46)
	at com.torodb.Main$2.run(Main.java:134)
Caused by: org.postgresql.util.PSQLException: ERROR: must be owner of type character varying or type jsonb
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:398)
	at com.zaxxer.hikari.proxy.StatementProxy.execute(StatementProxy.java:83)
	at com.zaxxer.hikari.proxy.StatementJavassistProxy.execute(StatementJavassistProxy.java)
	at com.torodb.torod.db.postgresql.meta.TorodbMeta.executeSql(TorodbMeta.java:314)
	at com.torodb.torod.db.postgresql.meta.TorodbMeta.createCast(TorodbMeta.java:340)
	at com.torodb.torod.db.postgresql.meta.TorodbMeta.<init>(TorodbMeta.java:71)
	at com.torodb.torod.db.sql.AbstractSqlDbWrapper.initialize(AbstractSqlDbWrapper.java:107)```

**Comment by gortiz** [comment]
Are you sure the user have root permissions? Because that error is shown
when the postgres user you are using doesn't have superadmin permissions.
We really want to remove that cast on future versions (it is the only
reason we need to execute torodb with a postgresql superadmin user). To be
honest, I think it is unecessary right now, but we didnt have time to test
it.

2015-10-01 18:29 GMT+02:00 EC <notifications@github.com>:

**Comment by evanccnyc** [comment]
I am 100% sure. I know Amazon restricts certain things you can do on RDS instances. This may be one of those times.

**Comment by ahachete** [comment]
Yes, that's the cause. RDS's "superuser" is not a real superuser but a somewhat restricted superuser. So we'll need to drop that --now infamous-- cast asap. Thanks for the report!

We will report back as soon as it is fixed.

**Comment by graingert** [comment]
@ahachete what's the status on RDS support?

**Comment by teoincontatto** [comment]
We removed the cast in our devel branch with #85. Now RDS should work with ToroDB.
