### ISSUE TITLE
ERROR c.t.t.d.e.DefaultExecutorFactory - System executor exception

### ISSUE THREAD

**Issue by zarmack** [torodb/torodb#24]
I'm inserting a register into a new collection, and ToroDB drops a strange error.

````javascript
> db.createCollection('notify');
> db.notify.insert({
...   "section": "nfs",
...   "sequence": "01",
...   "command": "2f6574632f696e69742e642f6e66732d636f6d6d6f6e2073746f70",
...   "on-fail-action": "00",
...   "on-success-action": "10",
...   "expected-exit-code": 0,
...   "exit-code": 0,
...   "output": "53746f7070696e67206e66732d636f6d6d6f6e20287669612073797374656d63746c293a206e66732d636f6d6d6f6e2e736572766963652e0a"
... });
````

The ToroDB's error is:
````
Starting ToroDB v0.22.1 listening on port 27017
539800 [torod-system-1] ERROR c.t.t.d.e.DefaultExecutorFactory - System executor exception
com.torodb.torod.core.exceptions.ToroRuntimeException: java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [{ ? = call "public"."reserve_doc_ids"(?, ?) }]; ERROR: function public.reserve_doc_ids(character varying, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
        at com.torodb.torod.db.executor.jobs.SystemDbCallable.onFail(SystemDbCallable.java:64) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:22) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.DefaultSystemExecutor$SystemRunnable.call(DefaultSystemExecutor.java:153) ~[torodb.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [{ ? = call "public"."reserve_doc_ids"(?, ?) }]; ERROR: function public.reserve_doc_ids(character varying, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
        at com.torodb.torod.db.sql.AbstractSqlDbConnection.reserveDocIds(AbstractSqlDbConnection.java:217) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.ReserveSubDocIdsCallable.call(ReserveSubDocIdsCallable.java:58) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.ReserveSubDocIdsCallable.call(ReserveSubDocIdsCallable.java:33) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.SystemDbCallable.failableCall(SystemDbCallable.java:72) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:20) ~[torodb.jar:na]
        ... 5 common frames omitted
Caused by: org.jooq.exception.DataAccessException: SQL [{ ? = call "public"."reserve_doc_ids"(?, ?) }]; ERROR: function public.reserve_doc_ids(character varying, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
        at org.jooq.impl.Utils.translate(Utils.java:1644) ~[torodb.jar:na]
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661) ~[torodb.jar:na]
        at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:373) ~[torodb.jar:na]
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:304) ~[torodb.jar:na]
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:257) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.Routines.reserveDocIds(Routines.java:68) ~[torodb.jar:na]
        at com.torodb.torod.db.sql.AbstractSqlDbConnection.reserveDocIds(AbstractSqlDbConnection.java:211) ~[torodb.jar:na]
        ... 9 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: function public.reserve_doc_ids(character varying, integer) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 15
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270) ~[torodb.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998) ~[torodb.jar:na]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255) ~[torodb.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570) ~[torodb.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420) ~[torodb.jar:na]
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:413) ~[torodb.jar:na]
        at com.zaxxer.hikari.proxy.PreparedStatementProxy.execute(PreparedStatementProxy.java:44) ~[torodb.jar:na]
        at com.zaxxer.hikari.proxy.CallableStatementJavassistProxy.execute(CallableStatementJavassistProxy.java) ~[torodb.jar:na]
        at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194) ~[torodb.jar:na]
        at org.jooq.impl.AbstractRoutine.execute0(AbstractRoutine.java:386) ~[torodb.jar:na]
        at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:344) ~[torodb.jar:na]
        ... 13 common frames omitted
539808 [torod-system-1] ERROR c.t.t.d.e.DefaultExecutorFactory - System executor exception
com.torodb.torod.core.exceptions.ToroRuntimeException: java.lang.IllegalArgumentException: At the present time Torod doesn't support '-' as identifier character. Only a alphanumeric letters and '_' are supported
        at com.torodb.torod.db.executor.jobs.SystemDbCallable.onFail(SystemDbCallable.java:64) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:22) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.DefaultSystemExecutor$SystemRunnable.call(DefaultSystemExecutor.java:153) ~[torodb.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: At the present time Torod doesn't support '-' as identifier character. Only a alphanumeric letters and '_' are supported
        at com.torodb.torod.db.postgresql.IdsFilter.filter(IdsFilter.java:42) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.IdsFilter.escapeAttributeName(IdsFilter.java:35) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.tables.SubDocTable.toColumnName(SubDocTable.java:244) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.tables.SubDocTable.<init>(SubDocTable.java:109) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.tables.SubDocTable.<init>(SubDocTable.java:100) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.tables.SubDocTable.<init>(SubDocTable.java:96) ~[torodb.jar:na]
        at com.torodb.torod.db.postgresql.meta.CollectionSchema.prepareSubDocTable(CollectionSchema.java:230) ~[torodb.jar:na]
        at com.torodb.torod.db.sql.AbstractSqlDbConnection.createSubDocTypeTable(AbstractSqlDbConnection.java:190) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.CreateSubDocTableCallable.call(CreateSubDocTableCallable.java:58) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.CreateSubDocTableCallable.call(CreateSubDocTableCallable.java:34) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.SystemDbCallable.failableCall(SystemDbCallable.java:72) ~[torodb.jar:na]
        at com.torodb.torod.db.executor.jobs.Job.call(Job.java:20) ~[torodb.jar:na]
        ... 5 common frames omitted
````

Many thanks,
Zarmack

**Comment by zarmack** [comment]
Sorry, I've forgotten, the PostgreSQL version is 9.4.3

````
torodb=# SELECT version();
                                            version
-----------------------------------------------------------------------------------------------
 PostgreSQL 9.4.3 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
(1 row)
````

**Comment by ahachete** [comment]
Hi @zarmack If you scroll down to the end of the stack trace, you will notice an error message stating that "At the present time Torod doesn't support '-' as identifier character. Only a alphanumeric letters and '_' are supported". This is the cause of the error. If you try to rather insert a document similar to:

 db.notify.insert({ "section": "nfs", "sequence": "01", "command": "2f6574632f696e69742e642f6e66732d636f6d6d6f6e2073746f70", "on_fail_action": "00", "on_success_action": "10", "expected_exit_code": 0, "exit_code": 0, "output": "53746f7070696e67206e66732d636f6d6d6f6e20287669612073797374656d63746c293a206e66732d636f6d6d6f6e2e736572766963652e0a" });
WriteResult({ "nInserted" : 1 })

it works.

Please let us know if it's required for you to work with dashes ("-") as part of the key names and we will work on that to be supported.

**Comment by zarmack** [comment]
@ahachete, thank you very much for the information.
Know that they aren't supported in indentifiers for me is enought.

Many thanks,
Zarmack
